version: '2.2'
services:
  metrics-service:
    image: metrics-service:latest
    restart: always
    environment:
      VICTORIA_METRICS_ADDRESS: "http://host.docker.internal:8428"
      HEXAGON_RESOLUTION: 4
      ONIONOO_INSTANCE: "host.docker.internal:8080"
    ports:
      - "3000:3000"
