services:
  api-service:
    image: api-service
    restart: always
    environment:
      VICTORIA_METRICS_ADDRESS: "http://host.docker.internal:8428"
      HEXAGON_RESOLUTION: 4
      ONIONOO_INSTANCE: "host.docker.internal:8080"
      GEODATADIR: "/usr/src/app/data/node_modules/geoip-lite/data"
      GEOTMPDIR: "/usr/src/app/data/node_modules/geoip-lite/tmp"
    ports:
      - "3000:3000"
    volumes:
      - ./data/:/usr/src/app/data
      - ./allowed-origins.json:/usr/src/app/config/allowed-origins.json
  api-cache:
    image: varnish
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./varnish-docker.vcl:/etc/varnish/default.vcl:ro
