version: '2.2'
services:
  api-service:
    image: api-service:latest
    restart: always
    environment:
      VICTORIA_METRICS_ADDRESS: "http://host.docker.internal:8428"
      HEXAGON_RESOLUTION: 4
    ports:
      - "3000:3000"
