name: Build and Push Docker Image

inputs:
  docker-username:
    required: true
  docker-password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push Docker image of service
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ inputs.docker-username }}/metrcis-service:${{ github.sha }},${{ inputs.docker-username }}/metrics-service:latest
